### ISSUE TITLE
Downloadable jar

### ISSUE THREAD

**Issue by crafter23456** [CobbleSword/CobbleProtocolLib#1]
**Make sure you're doing the following**
- [ x] You're using the latest build for your server version
- [ x] This isn't an issue caused by another plugin
- [ x] You've checked for duplicate issues
- [ x] You didn't use `/reload`

**Describe the question**
https://just-paste.it/oW0ZEr104X I tried to complie the src but it is 900kb big and it causes a big issue.

**Expected behavior**
No error message

**Comment by CyberFlameGO** [comment]
@crafter23456 if i’m not mistaken, this fork of protocollib isn’t necessary anymore. Sorry for the late response!

**Comment by crafter23456** [comment]
Problem is solved a long time ago
